# Generated by Django 4.1 on 2024-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ip',
        ),
        migrations.AddField(
            model_name='camera',
            name='hora_fin',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='camera',
            name='hora_inicio',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
