# Generated by Django 4.1 on 2024-11-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_camera_ip_camera_hora_fin_camera_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='camera',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
